### ISSUE TITLE
v0.53 released

### ISSUE THREAD

**Issue by alento-group** [jrsupplee/mailinabox#17]
Time for an update again.  

Thanks for this fork John!

**Comment by stylnchris** [comment]
John,

I reached out to @JoshData today regarding your PR.

https://github.com/mail-in-a-box/mailinabox/pull/1568

joshdata <https://app.slack.com/team/U09FVLSJU>  4:26 PM
<https://mailinabox.slack.com/archives/C09E3L9KM/p1618431990336500>
There's a pull request at
https://github.com/mail-in-a-box/mailinabox/pull/1568 and I left some
comments a year ago that were never addressed. So that's where we are.





Was wondering if you were planning on addressing them or just keeping the
fork?
